##States and abbreviations
SUPPORTED_STATES = ({'abbrv': 'AK', 'name': 'Alaska'},
                    {'abbrv': 'AS', 'name': 'American Samoa'},
                    {'abbrv': "AZ", 'name': 'Arizona'},
                    {'abbrv': "AR", 'name': 'Arkansas'},
                    {'abbrv': "AE", 'name': 'Armed Forces Europe'},
                    {'abbrv': "AP", 'name': 'Armed Forces Pacific'},
                    {'abbrv': "AA", 'name': 'Armed Forces the Americas'},
                    {'abbrv': "CA", 'name': 'California'},
                    {'abbrv': "CO", 'name': 'Colorado'},
                    {'abbrv': "CT", 'name': 'Connecticut'},
                    {'abbrv': "DE", 'name': 'Delaware'},
                    {'abbrv': "DC", 'name': 'District of Columbia'},
                    {'abbrv': "FM", 'name': 'Federated names of Micronesia'},
                    {'abbrv': "FL", 'name': 'Florida'},
                    {'abbrv': "GA", 'name': 'Georgia'},
                    {'abbrv': "GU", 'name': 'Guam'},
                    {'abbrv': "HI", 'name': 'Hawaii'},
                    {'abbrv': "ID", 'name': 'Idaho'},
                    {'abbrv': "IL", 'name': 'Illinois'},
                    {'abbrv': "IN", 'name': 'Indiana'},
                    {'abbrv': "IA", 'name': 'Iowa'},
                    {'abbrv': "KS", 'name': 'Kansas'},
                    {'abbrv': "KY", 'name': 'Kentucky'},
                    {'abbrv': "LA", 'name': 'Louisiana'},
                    {'abbrv': "ME", 'name': 'Maine'},
                    {'abbrv': "MH", 'name': 'Marshall Islands'},
                    {'abbrv': "MD", 'name': 'Maryland'},
                    {'abbrv': "MA", 'name': 'Massachusetts'},
                    {'abbrv': "MI", 'name': 'Michigan'},
                    {'abbrv': "MN", 'name': 'Minnesota'},
                    {'abbrv': "MS", 'name': 'Mississippi'},
                    {'abbrv': "MO", 'name': 'Missouri'},
                    {'abbrv': "MT", 'name': 'Montana'},
                    {'abbrv': "NE", 'name': 'Nebraska'},
                    {'abbrv': "NV", 'name': 'Nevada'},
                    {'abbrv': "NH", 'name': 'New Hampshire'},
                    {'abbrv': "NJ", 'name': 'New Jersey'},
                    {'abbrv': "NM", 'name': 'New Mexico'},
                    {'abbrv': "NY", 'name': 'New York'},
                    {'abbrv': "NC", 'name': 'North Carolina'},
                    {'abbrv': "ND", 'name': 'North Dakota'},
                    {'abbrv': "MP", 'name': 'Northern Mariana Islands'},
                    {'abbrv': "OH", 'name': 'Ohio'},
                    {'abbrv': "OK", 'name': 'Oklahoma'},
                    {'abbrv': "OR", 'name': 'Oregon'},
                    {'abbrv': "PA", 'name': 'Pennsylvania'},
                    {'abbrv': "PR", 'name': 'Puerto Rico'},
                    {'abbrv': "RI", 'name': 'Rhode Island'},
                    {'abbrv': "SC", 'name': 'South Carolina'},
                    {'abbrv': "SD", 'name': 'South Dakota'},
                    {'abbrv': "TN", 'name': 'Tennessee'},
                    {'abbrv': "TX", 'name': 'Texas'},
                    {'abbrv': "UT", 'name': 'Utah'},
                    {'abbrv': "VT", 'name': 'Vermont'},
                    {'abbrv': "VI", 'name': 'Virgin Islands, U.S.'},
                    {'abbrv': "VA", 'name': 'Virginia'},
                    {'abbrv': "WA", 'name': 'Washington'},
                    {'abbrv': "WV", 'name': 'West Virginia'},
                    {'abbrv': "WI", 'name': 'Wisconsin'},
                    {'abbrv': "WY", 'name': 'Wyoming'})


SUPPORTED_STATES_CHOICES = tuple([(x['abbrv'], x['name']) for x in SUPPORTED_STATES])                        
STATE_ABBREVIATIONS = tuple([k['abbrv'] for k in SUPPORTED_STATES])


