##States and abbreviations
SUPPORTED_STATES = ({'abbrv': 'AK', 'name': 'Alaska'},
                    {'abbrv': 'AS', 'name': 'American Samoa'},
                    {'abbrv': "AZ", 'name': 'Arizona'},
                    {'abbrv': "AR", 'name': 'Arkansas'},
                    {'abbrv': "AE", 'name': 'Armed Forces Europe'},
                    {'abbrv': "AP", 'name': 'Armed Forces Pacific'},
                    {'abbrv': "AA", 'name': 'Armed Forces the Americas'},
                    {'abbrv': "CA", 'name': 'California'},
                    {'abbrv': "CO", 'name': 'Colorado'},
                    {'abbrv': "CT", 'name': 'Connecticut'},
                    {'abbrv': "DE", 'name': 'Delaware'},
                    {'abbrv': "DC", 'name': 'District of Columbia'},
                    {'abbrv': "FM", 'name': 'Federated names of Micronesia'},
                    {'abbrv': "FL", 'name': 'Florida'},
                    {'abbrv': "GA", 'name': 'Georgia'},
                    {'abbrv': "GU", 'name': 'Guam'},
                    {'abbrv': "HI", 'name': 'Hawaii'},
                    {'abbrv': "ID", 'name': 'Idaho'},
                    {'abbrv': "IL", 'name': 'Illinois'},
                    {'abbrv': "IN", 'name': 'Indiana'},
                    {'abbrv': "IA", 'name': 'Iowa'},
                    {'abbrv': "KS", 'name': 'Kansas'},
                    {'abbrv': "KY", 'name': 'Kentucky'},
                    {'abbrv': "LA", 'name': 'Louisiana'},
                    {'abbrv': "ME", 'name': 'Maine'},
                    {'abbrv': "MH", 'name': 'Marshall Islands'},
                    {'abbrv': "MD", 'name': 'Maryland'},
                    {'abbrv': "MA", 'name': 'Massachusetts'},
                    {'abbrv': "MI", 'name': 'Michigan'},
                    {'abbrv': "MN", 'name': 'Minnesota'},
                    {'abbrv': "MS", 'name': 'Mississippi'},
                    {'abbrv': "MO", 'name': 'Missouri'},
                    {'abbrv': "MT", 'name': 'Montana'},
                    {'abbrv': "NE", 'name': 'Nebraska'},
                    {'abbrv': "NV", 'name': 'Nevada'},
                    {'abbrv': "NH", 'name': 'New Hampshire'},
                    {'abbrv': "NJ", 'name': 'New Jersey'},
                    {'abbrv': "NM", 'name': 'New Mexico'},
                    {'abbrv': "NY", 'name': 'New York'},
                    {'abbrv': "NC", 'name': 'North Carolina'},
                    {'abbrv': "ND", 'name': 'North Dakota'},
                    {'abbrv': "MP", 'name': 'Northern Mariana Islands'},
                    {'abbrv': "OH", 'name': 'Ohio'},
                    {'abbrv': "OK", 'name': 'Oklahoma'},
                    {'abbrv': "OR", 'name': 'Oregon'},
                    {'abbrv': "PA", 'name': 'Pennsylvania'},
                    {'abbrv': "PR", 'name': 'Puerto Rico'},
                    {'abbrv': "RI", 'name': 'Rhode Island'},
                    {'abbrv': "SC", 'name': 'South Carolina'},
                    {'abbrv': "SD", 'name': 'South Dakota'},
                    {'abbrv': "TN", 'name': 'Tennessee'},
                    {'abbrv': "TX", 'name': 'Texas'},
                    {'abbrv': "UT", 'name': 'Utah'},
                    {'abbrv': "VT", 'name': 'Vermont'},
                    {'abbrv': "VI", 'name': 'Virgin Islands, U.S.'},
                    {'abbrv': "VA", 'name': 'Virginia'},
                    {'abbrv': "WA", 'name': 'Washington'},
                    {'abbrv': "WV", 'name': 'West Virginia'},
                    {'abbrv': "WI", 'name': 'Wisconsin'},
                    {'abbrv': "WY", 'name': 'Wyoming'})


SUPPORTED_STATES_CHOICES = tuple([(x['abbrv'], x['name']) for x in SUPPORTED_STATES])                        
STATE_ABBREVIATIONS = tuple([k['abbrv'] for k in SUPPORTED_STATES])


TIME_ZONES = (
    'Pacific/Midway',
    'Pacific/Tahiti',
    'Pacific/Marquesas',
    'America/Adak',
    'Pacific/Gambier',
    'US/Alaska',
    'Pacific/Pitcairn',
    'US/Pacific',
    'US/Arizona',
    'US/Mountain',
    'America/Guatemala',
    'Pacific/Easter',
    'US/Central',
    'America/Bogota',
    'US/Eastern',
    'America/Caracas',
    'America/Santiago',
    'Canada/Atlantic',
    'America/Montevideo',
    'America/Sao_Paulo',
    'America/St_Johns',
    'America/Godthab',
    'America/Noronha',
    'Atlantic/Cape_Verde',
    'Atlantic/Azores',
    'Africa/Casablanca',
    'Europe/London',
    'Africa/Algiers',
    'Africa/Windhoek',
    'Europe/Amsterdam',
    'Africa/Harare',
    'Europe/Athens',
    'Africa/Nairobi',
    'Europe/Moscow',
    'Asia/Dubai',
    'Asia/Tehran',
    'Asia/Kabul',
    'Asia/Baku',
    'Asia/Karachi',
    'Asia/Calcutta',
    'Asia/Katmandu',
    'Asia/Yekaterinburg',
    'Asia/Colombo',
    'Asia/Rangoon',
    'Asia/Almaty',
    'Asia/Bangkok',
    'Asia/Krasnoyarsk',
    'Australia/Perth',
    'Asia/Irkutsk',
    'Asia/Tokyo',
    'Australia/Darwin',
    'Australia/Adelaide',
    'Asia/Yakutsk',
    'Australia/Brisbane',
    'Australia/Sydney',
    'Australia/Lord_Howe',
    'Asia/Vladivostok',
    'Pacific/Guadalcanal',
    'Pacific/Norfolk',
    'Asia/Magadan',
    'Pacific/Fiji',
    'Pacific/Auckland',
    'Pacific/Chatham',
    'Pacific/Enderbury'
    'Pacific/Kiritimati',
)
TIME_ZONE_CHOICES = tuple([(x, x) for x in TIME_ZONES])